---

version: '2'
services:
  centos_7:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_CentOS_7
      args:
        ANSIBLE_VERSION: 2.6.2
        ROLE_NAME: timorunge.sssd
        WORKDIR: /ansible
    environment:
      TRAVIS: ${TRAVIS}
      YML_TEST_FILE: test-from-sources.yml
  debian_9_4:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Debian_9.4
      args:
        ANSIBLE_VERSION: 2.6.2
        ROLE_NAME: timorunge.sssd
        WORKDIR: /ansible
    environment:
      TRAVIS: ${TRAVIS}
      YML_TEST_FILE: test-from-sources.yml
  ubuntu_18_04:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_Ubuntu_18.04
      args:
        ANSIBLE_VERSION: 2.6.2
        ROLE_NAME: timorunge.sssd
        WORKDIR: /ansible
    environment:
      TRAVIS: ${TRAVIS}
      YML_TEST_FILE: test-from-sources.yml
