---

- name: Configure SSSD service (from config)
  template:
    dest: /etc/sssd/sssd.conf
    group: sssd
    mode: 0400
    owner: sssd
    src: sssd.conf.j2
  when: sssd_config_type == "config"
  notify:
    - restart sssd

- name: Configure SSSD service (from file)
  file:
    dest: /etc/sssd/sssd.conf
    group: sssd
    mode: 0400
    owner: sssd
    src: "{{ sssd_config_file }}"
  when: sssd_config_type == "file"
  notify:
    - restart sssd
