---

- name: Install SSSD build dependencies
  package:
    name: "{{ sssd_build_dependency_pkgs | default(omit) }}"
    state: present
    update_cache: yes

- name: Create SSSD group
  group:
    name: "{{ sssd_group }}"
    state: present

- name: Create SSSD user
  user:
    create_home: no
    groups: "{{ sssd_group }}"
    name: "{{ sssd_user }}"
    shell: /bin/false

- name: Create directories
  file:
    group: "{{ item.value.group }}"
    mode: "{{ item.value.mode }}"
    owner: "{{ item.value.owner }}"
    path: "{{ item.key }}"
    state: directory
  with_dict: "{{ sssd_dirs | combine(sssd_additional_dirs) }}"
